### ISSUE TITLE
Search with ElasticSearch

### ISSUE THREAD

**Issue by MrZoule** [Gatsbylius/Gatsbylius#36]
IMHO, supporting only one search engine but the most used is better than supporting standard Sylius search and then having to go further with first clients needs.
A Sylius plugin for ElasticSearch already exists : https://sylius.com/plugin/2004/

**Comment by gkueny** [comment]
Hi thanks for your proposal.
Our team currently focus to release a MVP : https://github.com/Gatsbylius/gatsbylius-starter/issues/1

We will consider ElasticSearch for search later : https://github.com/Gatsbylius/gatsbylius-starter/issues/2
