### ISSUE TITLE
StorefrontUI?

### ISSUE THREAD

**Issue by pkarw** [Gatsbylius/Gatsbylius#49]
Great job! Greetings from the [vue-storefront](https://github.com/DivanteLtd/vue-storefront) team!
How about using the [StorefrontUI](https://github.com/DivanteLtd/storefront-ui/tree/react-setup) for the frontend layer? It's been designed just for that and we're [working hard on the React version](https://blog.vuestorefront.io/join-us-as-we-open-up-the-storefront-ui-for-reactjs/)

**Comment by gkueny** [comment]
Hello @pkarw  and thank you !

As you can see here https://github.com/Gatsbylius/Gatsbylius/pull/52 and here https://github.com/Gatsbylius/gatsbylius-starter/issues/1 we are currently take a break on our development to think about our technical choices and get ride of our Gatsby theme in favor of a starter.

[StorefrontUI](https://github.com/DivanteLtd/storefront-ui/tree/react-setup) seems really great and we weren't aware there was a react version going on.

Help you on that and use it in Gatsbylius starter sounds like a good idea. We will discuss it here https://github.com/Gatsbylius/gatsbylius-starter/issues/1

Thank you again for your message !

**Comment by gkueny** [comment]
@pkarw **StorefrontUI** seems promising, but without any documentation about it (react version) it's a bit hard to test it in our repo.
Do you have some documentation to install & use **StorefrontUI** in a react project ? 
I tried discord channel but with no response.

For now I copy-past github repo in our `src` folder & update some path.

**Comment by gkueny** [comment]
Hi, 

I test StorefrontUI a bit, but I think it wil not fit our need for now.
* Gatsby is fast & popular thanks to [Gatsby image](https://www.gatsbyjs.org/packages/gatsby-image/). But now, it's not possible to use it in StoreFrontUI component
* StroreFrontUI react version it's on early stage. We will reconsider it later
